# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest
  
variables:
  uisource: src
  uibuild: $(uisource)/build
  S3-target-folder: abc-company
  env: dev

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    pushd $(uisource)
    npm install
    npm run build
    popd
  displayName: 'npm install and run build'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      echo "$(agent.builddirectory)"
      ls -lart 
      echo "$(build.artifactstagingdirectory)"
      cd $(build.artifactstagingdirectory)
      ls -lart

- task: CopyFiles@1
  inputs:
    SourceFolder: '$(agent.builddirectory)'
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)'
    CleanTargetFolder: true
 
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(uibuild)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/build/$(Build.BuildNumber)-$(Build.DefinitionVersion)-$(env).zip'
    replaceExistingArchive: true
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/build/$(Build.BuildNumber)-$(Build.DefinitionVersion)-$(env).zip'
    ArtifactName: 'drop'
    publishLocation: 'Container'
    
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      cd $(Build.ArtifactStagingDirectory)/build
      ls -lart
        
- task: S3Upload@1
  inputs:
    awsCredentials: 's3-service-conn'
    regionName: 'us-east-1'
    bucketName: 'dev-demo-stage'
    sourceFolder: '$(Build.ArtifactStagingDirectory)/build'
    globExpressions: '*.zip'
    targetFolder: '$(S3-target-folder)'
    createBucket: true
