# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest
  
variables:
  directory: react-azure-demo
  S3-target-folder: abc-company

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'
  

- script: |
    npm run build
  displayName: 'npm build'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      echo "$(agent.builddirectory)"
      ls -lart 
      echo "$(build.artifactstagingdirectory)"
      cd $(build.artifactstagingdirectory)
      ls -lart
      echo 'Hello world'
    
- task: CopyFiles@1
  inputs:
    SourceFolder: '$(agent.builddirectory)'
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)'
    CleanTargetFolder: true
   
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    ArtifactName: 'drop'
    publishLocation: 'Container'
    StoreAsTar: true
- task: S3Upload@1
  inputs:
    awsCredentials: 's3-service-conn'
    regionName: 'us-east-1'
    bucketName: 'dev-demo-stage'
    sourceFolder: '$(Build.ArtifactStagingDirectory)'
    globExpressions: '*.zip'
    targetFolder: '$(S3-target-folder)'
    createBucket: true
